// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: invoices.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices
    (client_id, amount, date_of_issue, due_date, description, owner_id)
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING id,
    client_id,
    amount,
    date_of_issue,
    due_date,
    description,
    is_paid,
    created_at,
    updated_at
`

type CreateInvoiceParams struct {
	ClientID    pgtype.UUID      `json:"client_id"`
	Amount      pgtype.Int4      `json:"amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	OwnerID     pgtype.Int4      `json:"owner_id"`
}

type CreateInvoiceRow struct {
	ID          pgtype.UUID      `json:"id"`
	ClientID    pgtype.UUID      `json:"client_id"`
	Amount      pgtype.Int4      `json:"amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (CreateInvoiceRow, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ClientID,
		arg.Amount,
		arg.DateOfIssue,
		arg.DueDate,
		arg.Description,
		arg.OwnerID,
	)
	var i CreateInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Amount,
		&i.DateOfIssue,
		&i.DueDate,
		&i.Description,
		&i.IsPaid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM
    invoices
WHERE
    id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT
    id,
    client_id,
    amount,
    date_of_issue,
    due_date,
    description,
    is_paid,
    created_at,
    updated_at
FROM
    invoices
WHERE
    id = $1
AND
    owner_id = $2
`

type GetInvoiceByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.Int4 `json:"owner_id"`
}

type GetInvoiceByIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	ClientID    pgtype.UUID      `json:"client_id"`
	Amount      pgtype.Int4      `json:"amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (GetInvoiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, arg.ID, arg.OwnerID)
	var i GetInvoiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Amount,
		&i.DateOfIssue,
		&i.DueDate,
		&i.Description,
		&i.IsPaid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoices = `-- name: GetInvoices :many
SELECT
    i.id as id,
    c.name as client_id,
    i.amount,
    i.date_of_issue,
    i.due_date,
    i.description,
    i.is_paid,
    i.created_at,
    i.updated_at
FROM
    invoices i
JOIN clients c ON i.client_id = c.id
WHERE
    i.owner_id = $1
`

type GetInvoicesRow struct {
	ID          pgtype.UUID      `json:"id"`
	ClientID    string           `json:"client_id"`
	Amount      pgtype.Int4      `json:"amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetInvoices(ctx context.Context, ownerID pgtype.Int4) ([]GetInvoicesRow, error) {
	rows, err := q.db.Query(ctx, getInvoices, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoicesRow
	for rows.Next() {
		var i GetInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Amount,
			&i.DateOfIssue,
			&i.DueDate,
			&i.Description,
			&i.IsPaid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoicesByClientID = `-- name: GetInvoicesByClientID :many
SELECT
    id,
    client_id,
    amount,
    date_of_issue,
    due_date,
    description,
    is_paid,
    created_at,
    updated_at
FROM
    invoices
WHERE
    client_id = $1
AND
    owner_id = $2
`

type GetInvoicesByClientIDParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	OwnerID  pgtype.Int4 `json:"owner_id"`
}

type GetInvoicesByClientIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	ClientID    pgtype.UUID      `json:"client_id"`
	Amount      pgtype.Int4      `json:"amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetInvoicesByClientID(ctx context.Context, arg GetInvoicesByClientIDParams) ([]GetInvoicesByClientIDRow, error) {
	rows, err := q.db.Query(ctx, getInvoicesByClientID, arg.ClientID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoicesByClientIDRow
	for rows.Next() {
		var i GetInvoicesByClientIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Amount,
			&i.DateOfIssue,
			&i.DueDate,
			&i.Description,
			&i.IsPaid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :exec
UPDATE
    invoices
SET
    client_id = $1,
    amount = $2,
    date_of_issue = $3,
    due_date = $4,
    description = $5,
    is_paid = $6,
    updated_at = NOW()
WHERE
    id = $7
`

type UpdateInvoiceParams struct {
	ClientID    pgtype.UUID      `json:"client_id"`
	Amount      pgtype.Int4      `json:"amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	ID          pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) error {
	_, err := q.db.Exec(ctx, updateInvoice,
		arg.ClientID,
		arg.Amount,
		arg.DateOfIssue,
		arg.DueDate,
		arg.Description,
		arg.IsPaid,
		arg.ID,
	)
	return err
}
