// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: invoices.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices
    (client_id, total_amount, date_of_issue, due_date, description)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING id,
    client_id,
    total_amount,
    date_of_issue,
    due_date,
    description,
    is_paid,
    created_at,
    updated_at
`

type CreateInvoiceParams struct {
	ClientID    pgtype.UUID      `json:"client_id"`
	TotalAmount pgtype.Int4      `json:"total_amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
}

type CreateInvoiceRow struct {
	ID          pgtype.UUID      `json:"id"`
	ClientID    pgtype.UUID      `json:"client_id"`
	TotalAmount pgtype.Int4      `json:"total_amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (CreateInvoiceRow, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ClientID,
		arg.TotalAmount,
		arg.DateOfIssue,
		arg.DueDate,
		arg.Description,
	)
	var i CreateInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TotalAmount,
		&i.DateOfIssue,
		&i.DueDate,
		&i.Description,
		&i.IsPaid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM
    invoices
WHERE
    id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT 
    id,
    client_id,
    total_amount,
    date_of_issue,
    due_date,
    description,
    is_paid,
    created_at,
    updated_at
FROM
    invoices
WHERE
    id = $1
`

type GetInvoiceByIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	ClientID    pgtype.UUID      `json:"client_id"`
	TotalAmount pgtype.Int4      `json:"total_amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (GetInvoiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i GetInvoiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TotalAmount,
		&i.DateOfIssue,
		&i.DueDate,
		&i.Description,
		&i.IsPaid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoices = `-- name: GetInvoices :many
SELECT
    id,
    client_id,
    total_amount,
    date_of_issue,
    due_date,
    description,
    is_paid,
    created_at,
    updated_at
FROM
    invoices
`

type GetInvoicesRow struct {
	ID          pgtype.UUID      `json:"id"`
	ClientID    pgtype.UUID      `json:"client_id"`
	TotalAmount pgtype.Int4      `json:"total_amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetInvoices(ctx context.Context) ([]GetInvoicesRow, error) {
	rows, err := q.db.Query(ctx, getInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoicesRow
	for rows.Next() {
		var i GetInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TotalAmount,
			&i.DateOfIssue,
			&i.DueDate,
			&i.Description,
			&i.IsPaid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoicesByClientID = `-- name: GetInvoicesByClientID :many
SELECT
    id,
    client_id,
    total_amount,
    date_of_issue,
    due_date,
    description,
    is_paid,
    created_at,
    updated_at
FROM
    invoices
WHERE
    client_id = $1
`

type GetInvoicesByClientIDRow struct {
	ID          pgtype.UUID      `json:"id"`
	ClientID    pgtype.UUID      `json:"client_id"`
	TotalAmount pgtype.Int4      `json:"total_amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetInvoicesByClientID(ctx context.Context, clientID pgtype.UUID) ([]GetInvoicesByClientIDRow, error) {
	rows, err := q.db.Query(ctx, getInvoicesByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvoicesByClientIDRow
	for rows.Next() {
		var i GetInvoicesByClientIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TotalAmount,
			&i.DateOfIssue,
			&i.DueDate,
			&i.Description,
			&i.IsPaid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :exec
UPDATE
    invoices
SET
    client_id = $1,
    total_amount = $2,
    date_of_issue = $3,
    due_date = $4,
    description = $5,
    is_paid = $6,
    updated_at = NOW()
WHERE
    id = $7
`

type UpdateInvoiceParams struct {
	ClientID    pgtype.UUID      `json:"client_id"`
	TotalAmount pgtype.Int4      `json:"total_amount"`
	DateOfIssue pgtype.Timestamp `json:"date_of_issue"`
	DueDate     pgtype.Timestamp `json:"due_date"`
	Description pgtype.Text      `json:"description"`
	IsPaid      pgtype.Bool      `json:"is_paid"`
	ID          pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) error {
	_, err := q.db.Exec(ctx, updateInvoice,
		arg.ClientID,
		arg.TotalAmount,
		arg.DateOfIssue,
		arg.DueDate,
		arg.Description,
		arg.IsPaid,
		arg.ID,
	)
	return err
}
