// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateUser(ctx context.Context, id int32) error
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (CreateCampaignRow, error)
	// Clients CRUD operations
	CreateClient(ctx context.Context, arg CreateClientParams) (CreateClientRow, error)
	// Companies CRUD operations
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (CreateCompanyRow, error)
	// Leads CRUD operations
	CreateLead(ctx context.Context, arg CreateLeadParams) (CreateLeadRow, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error
	DeleteLead(ctx context.Context, arg DeleteLeadParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	DeleteUser(ctx context.Context, id int32) error
	GetBoard(ctx context.Context, ownerID pgtype.Int4) ([]GetBoardRow, error)
	GetCampaignByID(ctx context.Context, arg GetCampaignByIDParams) (GetCampaignByIDRow, error)
	GetCampaigns(ctx context.Context, ownerID pgtype.Int4) ([]GetCampaignsRow, error)
	GetClientByID(ctx context.Context, arg GetClientByIDParams) (GetClientByIDRow, error)
	GetClients(ctx context.Context, arg GetClientsParams) ([]GetClientsRow, error)
	GetClientsWithCompanyInfo(ctx context.Context, arg GetClientsWithCompanyInfoParams) ([]GetClientsWithCompanyInfoRow, error)
	GetCompanies(ctx context.Context, arg GetCompaniesParams) ([]GetCompaniesRow, error)
	GetCompanyByID(ctx context.Context, arg GetCompanyByIDParams) (GetCompanyByIDRow, error)
	GetLeadByID(ctx context.Context, arg GetLeadByIDParams) (GetLeadByIDRow, error)
	GetLeads(ctx context.Context, arg GetLeadsParams) ([]GetLeadsRow, error)
	GetReviewsByCampaignID(ctx context.Context, campaignID int32) ([]Review, error)
	GetSentimentCountByCampaignID(ctx context.Context, arg GetSentimentCountByCampaignIDParams) (int64, error)
	GetTotalNumberOfClients(ctx context.Context, ownerID pgtype.Int4) (int64, error)
	GetTotalNumberOfCompanies(ctx context.Context, ownerID pgtype.Int4) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id int32) (Users, error)
	GetUserByUsername(ctx context.Context, username string) (Users, error)
	GetUsers(ctx context.Context) ([]Users, error)
	SearchClients(ctx context.Context, arg SearchClientsParams) ([]SearchClientsRow, error)
	SearchCompanies(ctx context.Context, arg SearchCompaniesParams) ([]SearchCompaniesRow, error)
	SearchLeads(ctx context.Context, arg SearchLeadsParams) ([]SearchLeadsRow, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) error
	UpdateLead(ctx context.Context, arg UpdateLeadParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
